services:
  app:
    image: ghcr.io/victorikhianosen/pakasso-internetbanking:latest
    container_name: pakasso_internetbanking
    restart: always
    ports:
      - "3006:3006"
    env_file:
      - .env

# services:
#   app:
#     build: .
#     container_name: pakasso_internetbanking
#     ports:
#       - "3006:3006"
#     env_file:
#       - .env
