services:
  app:
    image: ghcr.io/victorikhianosen/pakasso-internetbanking:latest
    container_name: pakasso_internetbanking
    restart: always
    ports:
      - "3006:3006"
    env_file:
      - .env